$schema: "/templating/schema.json"

title: My StartPage
theme: Emerald Tides
clock: true
sections:
  - title: Work
    blocks:
      - title: Communication
        links:
          - title: Teams
            href: http://teams.microsoft.com
          - title: Slack
            href: https://slack.com
          - title: Outlook
            href: http://outlook.live.com
      - title: Search
        searchFields:
          - title: Search on google
            href: https://www.google.com/search?q=[search-term]
        links:
          - title: Wikipedia
            href: https://wikipedia.com
          - title: Translate
            href: https://translate.google.com/
      - title: Daily
        links:
          - title: To Do
            href: https://to-do.office.com/
          - title: Jira
            href: https://id.atlassian.com/
  - title: Personal
    blocks:
      - title: Socials
        links:
          - href: https://www.instagram.com
            title: Instagram
          - href: https://www.facebook.com
            title: Facebook
      - title: Home
        links:
          - title: To Do
            href: https://to-do.office.com/
          - title: Groceries
            href: https://groceries.com/
      - title: Hobbies
        links:
          - title: Lego
            href: https://www.lego.com/
          - title: Marklin
            href: https://www.marklin.com/
      - title: Entertainment
        links:
          - title: Youtube
            href: https://youtube.com
          - title: Netflix
            href: https://netflix.com