# .github/workflows/release-publish.yml
name: Publish Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: ./.github/actions/setup-node-deps

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Bump dev version
        run: |
          NEXT=$(node -p "require('semver').inc(require('./package.json').version, 'patch') + '-dev'")
          npm version "$NEXT" --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore: start next development iteration $NEXT"
          git push origin HEAD
